config/routes.rb
Rails.application.routes.draw do
  resources :requests
  get 'messages/new'

  get 'sessions/new'

  root 'sessions#new'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

	get '/messages', to: 'messages#messages'
	post '/send', to: 'messages#create'
	get '/error', to: 'messages#error'
	get '/LandLord/Send', to:'messages#landLord_send'
	get 'LandLord/Error', to: 'messages#landLord_error'
	get '/reply', to: 'messages#reply'
  

  get '/home', to: 'movies#dashboard'

  get '/tenant_maintenance', to: 'requests#tenant_maintenance'

  get '/requestform', to: 'movies#requestform'
  get '/documents', to: 'movies#documents'
  get '/pay_rent', to: 'movies#pay_rent'
  get '/profile', to: 'movies#profile'
  get '/settings', to: 'movies#settings'
  
  get '/send', to: 'movies#send'
  get '/LandLord', to: 'movies#landLord'#, as: 'landLord'
  get '/LandLord/TennantList', to: 'movies#tennantList', as: 'tennantList'
  get '/LandLord/Messages', to: 'movies#messages_landLord', as: 'landLordMessages'
  get '/LandLord/Documents', to: 'movies#documents_landLord', as: 'landLordDocuments'
  get '/LandLord/maintenance', to: 'movies#maintenance', as: 'maintenance'
  get '/LandLord/Profile', to: 'movies#profile_landLord', as: 'landLordProfile'
  resources :tenant

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'


  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  resources :users
	resources :messages
end

app/controllers/movies_controller.rb
#Controller for Landlord
class MoviesController < ApplicationController

  before_filter :authenticate_user!
  layout :determine_layout


  def determine_layout
    current_user.group == "landlord" ? "landlord_layout" : "application"
    #if current_user.group == "landlord"
    #   root :to => 'movies#Landlord'
    #end
  end
  #layout "application"
  
  def movie_params

    params.require(:tenants).permit(:tenant, :rent, :unreadMess, :maintenance,  :propLoc)
  end

  def show


  #filler controller definitions in order to try to display something on
  #the landlord page which could be modified fairly easily. instead of set
  #values the instance variables will have functions to calculate the correct
  #amount of money, messages, and documents
  end

  def profile

  end
  
  def maintenance 
    @allRequests = Request.all.order(:created_at)
    
    @change = params[:stat]
    if (@change != nil)
      newRequest = Request.find(params[:stat]) 
      if (newRequest.status != "complete")
        Request.create!(:address => newRequest.address, :name => newRequest.name, :email => newRequest.email, :option => newRequest.option,:body => newRequest.body, :status => "complete",:created_at => newRequest.created_at)
        newRequest.destroy
        @allRequests = Request.all.order(:created_at)
      end
    end 
    
end 
  def landLord
    @tenant = Tenant.all
    @money = 0
    @messages = 0
    @tenantTotal = Tenant.all.count
    @tenant.each do |tenant|
      @money += tenant.rent.to_i
    end
    @tenant.each do |tenant|
      @messages += tenant.unreadMess.to_i
    end
    @totalMoney = @money
    @totalMessages = @messages
  end

  def tennantList
    @allTenants = Tenant.all
    @sorted = params[:sort]
    if (@sorted == "tenant")
      @allTenants = Tenant.all.order(@sorted)
    else
      @allTenants = Tenant.all.order(@sorted).reverse
    end
  
  end
  def requestform
  end
  
  def messages_landLord
  end
  def profile_landLord
  end
  
end

app/helpers/movies_helper.rb
#Helper for Movies
module MoviesHelper
  # Checks if a number is odd:
end
  

app/views/movies/dashboard.html.haml
//%h1 Welcome Tenants
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Tenant Box Home
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %link{:href => "https://www.w3schools.com/w3css/4/w3.css", :rel => "stylesheet"}/
    %link{:href => "assets/stylesheet/w3.css", :rel => "stylesheet"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Raleway", :rel => "stylesheet"}/
    %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css", :rel => "stylesheet"}/
    :css
      html,body,h1,h2,h3,h4,h5 {font-family: "Raleway", sans-serif}
      
      .w3-opacity, .w3-hover-opacity:hover{
        display: inline;
      }

          
    %body
      .w3-panel.w3-clear.w3-center
        %h2.w3-opacity Welcome 
        %h2.w3-opacity= current_user.name.capitalize
        %h2.w3-opacity !        
    / Overlay effect when opening sidebar on small screens
    
    / !PAGE CONTENT!
    .w3-main{:style => "margin-left:50px;margin-top:43px;"}
      / Header
      %body.w3-container{:style => "padding-top:22px"}

        %h5
          %b
            %i.fa.fa-dashboard
            My Dashboard
      .w3-row-padding.w3-margin-bottom
        .w3-quarter
          .w3-container.w3-red.w3-padding-16
            .w3-left
              %i.fa.fa-credit-card.w3-xxxlarge
            .w3-right
              %h3 Due: $950
              %h3 Date Due: 1st of the Month
            .w3-clear
              %h4= link_to "Payments", pay_rent_path
        .w3-quarter
          .w3-container.w3-teal.w3-padding-16
            .w3-left
              %i.fa.fa-comment.w3-xxxlarge
            .w3-right
              %h3 (#{get_received.count})
            .w3-clear
              %h4= link_to "Messages", messages_path
        .w3-quarter
          .w3-container.w3-blue.w3-padding-16
            .w3-left
              %i.fa.fa-male.w3-xxxlarge
            .w3-right
              %h3 
            .w3-clear
              %h4= link_to "Maintenance requests", tenant_maintenance_path
        // .w3-quarter
        //   .w3-container.w3-orange.w3-text-white.w3-padding-16
        //     .w3-left
        //       %i.fa.fa-file-text.w3-xxxlarge
        //     .w3-right
        //       %h3 4
        //     .w3-clear
        //     %h4 Documents
      //%h2= link_to "LandLord Dashboard", landLord_path

         
      

/%table#tenants
/  %thead
/    %tr
/      %th Dashboard
/      //%td= link_to "Dashboard", tenant_path(dashboard)
/      %th Maintenance
/      %th Message
/      %th Documents
/      %th Payment


/%h1.align Profile 

/%img{:src => "/images/download.png"}

/%table#user.center
/  %tbody 
/    %tr
/      %td Name:
/    %br
/    %tr
/      %td Age: 
  

/%html
/%h1.align Profile 

/%img{:src => "/images/download.png"}

/%table#user.center
/  %tbody 
/    %tr
/      %td Name:
/    %br
/    %tr
/      %td Age: 
      
/%div
     

/	%head
/		%title= yield(:title)
/		= yield(:head)
/	%body
/		%nav
/			%a{ :href => "/views/tenant/dashboard", :title => "Dashboard" }
/			%a{ :href => "/views/tenant/maintenance", :title => "Maintenance" }
/			%a{ :href => "/views/tenant/message", :title => "Message" }
/			%a{ :href => "/views/tenant/docs", :title => "Documents" }
/			%a{ :href => "/views/tenant/payment", :title => "Payment" }
/		#content

/			= yield

app/views/movies/documents.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Documents
    %meta{:charset => "UTF-8"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %link{:href => "https://www.w3schools.com/w3css/4/w3.css", :rel => "stylesheet"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Raleway", :rel => "stylesheet"}/
    %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css", :rel => "stylesheet"}/
    :css
      html,body,h1,h2,h3,h4,h5 {font-family: "Raleway", sans-serif}
      
  %body
    .w3-panel.w3-clear.w3-center
      %h2.w3-opacity Documents

app/views/movies/landLord.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Tenant Box Home
    %meta{:charset => "UTF-8"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %link{:href => "https://www.w3schools.com/w3css/4/w3.css", :rel => "stylesheet"}/
    %link{:href => "assets/stylesheet/w3.css", :rel => "stylesheet"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Raleway", :rel => "stylesheet"}/
    %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css", :rel => "stylesheet"}/
    :css
      html,body,h1,h2,h3,h4,h5 {font-family: "Raleway", sans-serif}
      
      .w3-opacity, .w3-hover-opacity:hover{
        display: inline;
      }
          
    %body
      .w3-panel.w3-clear.w3-center
        %h2.w3-opacity Welcome 
        %h2.w3-opacity= current_user.name.capitalize
        %h2.w3-opacity !
    / Overlay effect when opening sidebar on small screens
    
    / !PAGE CONTENT!
    .w3-main{:style => "margin-left:50px;margin-top:43px;"}
      / Header
      %body.w3-container{:style => "padding-top:22px"}

        %h5
          %b
            %i.fa.fa-dashboard
            My Dashboard
      .w3-row-padding.w3-margin-bottom
        .w3-quarter
          .w3-container.w3-red.w3-padding-16
            .w3-left
              %i.fa.fa-credit-card.w3-xxxlarge
            .w3-right
              %h3 Total Balance Due: $#{@totalMoney}
            .w3-clear
            %h4
        .w3-quarter
          .w3-container.w3-teal.w3-padding-16
            .w3-left
              %i.fa.fa-comment.w3-xxxlarge
            .w3-right
              %h3 Total Unread Messages (#{get_received.count})
            .w3-clear
            %h4= link_to "Messages", landLordMessages_path
        .w3-quarter
          .w3-container.w3-blue.w3-padding-16
            .w3-left
              %i.fa.fa-male.w3-xxxlarge
            .w3-right
              %h3 Total Tenants #{@tenantTotal}
            .w3-clear
            %h4= link_to "Tennant List", tennantList_path
      /%h2= link_to "LandLord Dashboard", landLord_path








/%table#tenants
/  %thead
/    %tr
/      %th= link_to "Dashboard", landLord_path
/      %th= link_to "Tennant List", tennantList_path
/      %th= link_to "Messages", landLordMessages_path
/      %th= link_to "Documents", landLordDocuments_path
/      
/%table#tenants
/  %tbody 
/    %tr
/      %td Total Balance Due: #{@totalMoney}
/    %br
/    %tr
/      %td Total Unread Messages #{@totalMessages}
/    %br
/    %tr
/      %td Total Unopened Documents #{@totalDocuments}
/    %br

app/views/movies/maintenance.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Maintenance Requests
    %meta{:charset => "UTF-8"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %link{:href => "https://www.w3schools.com/w3css/4/w3.css", :rel => "stylesheet"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Raleway", :rel => "stylesheet"}/
    %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css", :rel => "stylesheet"}/
    :css
      html,body,h1,h2,h3,h4,h5 {font-family: "Raleway", sans-serif}
         
  %body
    .w3-panel.w3-clear.w3-center
      %h2.w3-opacity Maintenance Requests
    :css
      * {
          box-sizing: border-box;
      }
      
      input[type=text], select, textarea {
          width: 100%;
          padding: 12px;
          border: 1px solid #ccc;
          border-radius: 4px;
          resize: vertical;
      }
      
      label {
          padding: 12px 12px 12px 0;
          display: inline-block;
      }
      
      input[type=submit] {
          background-color: #4CAF50;
          color: white;
          padding: 12px 20px;
          border: none;
          border-radius: 4px;
          cursor: pointer;
          float: right;
      }
      
      input[type=submit]:hover {
          background-color: #45a049;
      }
      
      .test{
        background-color: #000;
      }
      .container {
          border-radius: 5px;
          background-color: #f2f2f2;
          padding: 20px;
      }
      
      .col-25 {
          float: left;
          width: 25%;
          margin-top: 6px;
          margin-left: 200px;
      }
      
      .col-75 {
          float: left;
          width: 75%;
          margin-top: 6px;
          margin-left: 200px;
      }
      
      /* Clear floats after the columns */
      .row:after {
          content: "";
          display: table;
          clear: both;
      }
      
      /* Responsive layout - when the screen is less than 600px wide, make the two columns stack on top of each other instead of next to each other */
      @media screen and (max-width: 600px) {
          .col-25, .col-75, input[type=submit] {
              width: 100%;
              margin-top: 0;
          }
      }
      button {
        border: none;
        outline: 0;
        display: inline-block;
        padding: 8px;
        color: white;
        background-color: #000;
        text-align: center;
        cursor: pointer;
        width: 30%;
        font-size: 18px;
        margin: center;
        margin-left: 500px;
        margin-top: 40px;
      }
  %body
    .w3-container
      %table.w3-table-all
        %thead
          %tr.w3-blue
            %th Tenant Name
            %th Address
            %th Email
            %th Request
            %th Subject
            %th Time of Request
            %th Status
        %tbody
          - @allRequests.each do |main|
            %tr.w3-white
              %th= main.name
              %th= main.address
              %th= main.email
              %th= main.option
              %th= main.body
              %th= main.created_at
              %th=link_to main.status, maintenance_path(stat: main)

app/views/movies/messages_landLord.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title LandLord Messages
    %meta{:charset => "UTF-8"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %link{:href => "https://www.w3schools.com/w3css/4/w3.css", :rel => "stylesheet"}/
    %link{:href => "https://fonts.googleapis.com/css?family=RobotoDraft", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css", :rel => "stylesheet"}/
    :css
      html,body,h1,h2,h3,h4,h5 {font-family: "RobotoDraft", "Roboto", sans-serif}
      .w3-bar-block .w3-bar-item {padding: 16px}
      
      #mySidebar{
        overflow: scroll; 
       }
       .newemail{
        width: 100%;
        padding: 3px;
        border: 1px solid #ccc;
        border-radius: 4px;
        resize: vertical;
      }
      .send{
          background-color: #4CAF50;
          color: white;
          padding: 12px 20px;
          border: none;
          border-radius: 4px;
          cursor: pointer;
          float: left;
      }
      .cancel{
          background-color: #2196F3;
          color: white;
          padding: 12px 20px;
          border: none;
          border-radius: 4px;
          cursor: pointer;
          float: right;
      }

  %body
    / Side Navigation
    %nav#mySidebar.w3-sidebar.w3-bar-block.w3-collapse.w3-white.w3-animate-left.w3-card.fixed{:style => "z-index:3;width:320px"}
      %a.w3-bar-item.w3-button.w3-hide-large.w3-large{:href => "javascript:void(0)", :onclick => "w3_close()", :title => "Close Sidemenu"}
        Close
        %i.fa.fa-remove
      %a.w3-bar-item.w3-button.w3-dark-grey.w3-button.w3-hover-black.w3-left-align{:href => "javascript:void(0)", :onclick => "document.getElementById('id01').style.display='block'"}
        New Message
        %i.w3-padding.fa.fa-pencil
      %a#myBtn.w3-bar-item.w3-button{:href => "javascript:void(0)", :onclick => "myFunc('Demo1')"}
        %i.fa.fa-inbox.w3-margin-right>
        Inbox (#{get_received.count})
        %i.fa.fa-caret-down.w3-margin-left
      #Demo1.w3-hide.w3-animate-left
        -get_received.each do |message|
          %a.w3-bar-item.w3-button.w3-border-bottom.test.w3-hover-light-grey{:href => "javascript:void(0)", :onclick => "openMail('#{message.id}');w3_close();"}
            .w3-container
              /%img.w3-round.w3-margin-right{:src => "/w3images/avatar3.png", :style => "width:15%;"}/
              %span.w3-opacity.w3-large #{message.receiver}
              %h6 Subject: #{message.subject}
              %p #{message.content}
      %a#myBtn.w3-bar-item.w3-button{:href => "javascript:void(0)", :onclick => "myFunc('Demo2')"}
        %i.fa.fa-paper-plane.w3-margin-right>
        Sent(#{get_sent.count})
        %i.fa.fa-caret-down.w3-margin-left
      #Demo2.w3-hide.w3-animate-left
        -get_sent.each do |message|
          %a.w3-bar-item.w3-button.w3-border-bottom.test.w3-hover-light-grey{:href => "javascript:void(0)", :onclick => "openMail('#{message.id}');w3_close();"}
            .w3-container
              /%img.w3-round.w3-margin-right{:src => "/w3images/avatar3.png", :style => "width:15%;"}/
              %span.w3-opacity.w3-large #{message.sender}
              %h6 Subject: #{message.subject}
              %p #{message.content}
      %a.w3-bar-item.w3-button{:href => "#"}
        %i.fa.fa-hourglass-end.w3-margin-right>
        Drafts
      %a.w3-bar-item.w3-button{:href => "#"}
        %i.fa.fa-trash.w3-margin-right>
        Trash
    / Modal that pops up when you click on "New Message"
    #id01.w3-modal{:style => "z-index:4"}
      .w3-modal-content.w3-animate-zoom
        .w3-container.w3-padding.w3-light-grey.w3-large
          %span.w3-button.w3-blue.w3-right.w3-large{:onclick => "document.getElementById('id01').style.display='none'"}
            %i.fa.fa-remove
          %h2{:align => "center"} Send Mail
          =form_for(:message, url: send_path) do |f|
            =f.label :to
            .w3-input.w3-border.w3-margin-bottom=f.email_field :receiver

            =f.label :from
            .w3-input.w3-border.w3-margin-bottom=f.email_field :sender

            =f.label :subject
            .w3-input.w3-border.w3-margin-bottom=f.text_field :subject

            =f.label :content
            .w3-input.w3-bordcer.w3-margin-bottom=f.text_area :content
            
            .w3-section
            %i.fa.fa-remove.w3-right
            %a.w3-button.w3-blue.w3-right{:onclick => "document.getElementById('id01').style.display='none'"}
              Cancel  
            /%i.fa.fa-remove.w3-right
            %a.w3-button.w3-clear.w3-left{:onclick => "document.getElementById('id01').style.display='none'"}=f.submit "Send" 
            
    %body
      .w3-panel.w3-clear.w3-center
        %h2.w3-opacity Messages  
    / Overlay effect when opening the side navigation on small screens
    #myOverlay.w3-overlay.w3-hide-large.w3-animate-opacity{:onclick => "w3_close()", :style => "cursor:pointer", :title => "Close Sidemenu"}
    / Page content
    .w3-main{:style => "margin-left:320px;"}
      %i.fa.fa-bars.w3-button.w3-white.w3-hide-large.w3-xlarge.w3-margin-left.w3-margin-top{:onclick => "w3_open()"}
      /%a.w3-hide-large.w3-red.w3-button.w3-right.w3-margin-top.w3-margin-right{:href => "javascript:void(0)", :onclick => "document.getElementById('id01').style.display='block'"}
      -get_received.each do |message|
        .w3-container.person{:id => "#{message.id}"}
          %br/
          /%img.w3-round.w3-animate-top{:src => "/w3images/avatar3.png", :style => "width:20%"}/
          %h5.w3-opacity Subject: #{message.subject}
          %h4
            %i.fa.fa-clock-o
            From #{message.sender}, #{message.created_at}
          %a.w3-button.w3-light-grey{:href => "/LandLord/Reply"}
            Reply
            %i.w3-margin-left.fa.fa-mail-reply
          %hr/
          %p #{message.content}
      -get_sent.each do |message|
        .w3-container.person{:id => "#{message.id}"}
          %br/
          /%img.w3-round.w3-animate-top{:src => "/w3images/avatar3.png", :style => "width:20%"}/
          %h5.w3-opacity Subject: #{message.subject}
          %h4
            %i.fa.fa-clock-o
            To #{message.receiver}, #{message.created_at}
          %hr/
          %p #{message.content}
    :javascript
      var openInbox = document.getElementById("myBtn");
      openInbox.click();
      
      function w3_open() {
          document.getElementById("mySidebar").style.display = "block";
          document.getElementById("myOverlay").style.display = "block";
      }
      function w3_close() {
          document.getElementById("mySidebar").style.display = "none";
          document.getElementById("myOverlay").style.display = "none";
      }
      
      function myFunc(id) {
          var x = document.getElementById(id);
          if (x.className.indexOf("w3-show") == -1) {
              x.className += " w3-show"; 
              x.previousElementSibling.className += " w3-blue";
          } else { 
              x.className = x.className.replace(" w3-show", "");
              x.previousElementSibling.className = 
              x.previousElementSibling.className.replace(" w3-blue", "");
          }
      }
      function validateForm() {
        var x = document.forms["myForm"]["fname"].value;
          if (x == ""){
            alert("Name must be filled out");
            return false;
          }
      }
      openMail("Borge")
      function openMail(personName) {
          var i;
          var x = document.getElementsByClassName("person");
          for (i = 0; i < x.length; i++) {
             x[i].style.display = "none";
          }
          x = document.getElementsByClassName("test");
          for (i = 0; i < x.length; i++) {
             x[i].className = x[i].className.replace(" w3-light-grey", "");
          }
          document.getElementById(personName).style.display = "block";
          event.currentTarget.className += " w3-light-grey";
      }
    :javascript
      var openTab = document.getElementById("firstTab");
      openTab.click();

app/views/movies/new.html.haml
%h1 Create New Movie

= form_tag movies_path do

  = label :movie, :title, 'Title'
  = text_field :movie, 'title'

  = label :movie, :rating, 'Rating'
  = select :movie, :rating, ['G','PG','PG-13','R','NC-17']

  = label :movie, :release_date, 'Released On'
  = date_select :movie, :release_date

  = submit_tag 'Save Changes'

app/views/movies/requestform.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Requests
    %meta{:charset => "UTF-8"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %link{:href => "https://www.w3schools.com/w3css/4/w3.css", :rel => "stylesheet"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Raleway", :rel => "stylesheet"}/
    %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css", :rel => "stylesheet"}/
    
    %body
    .w3-panel.w3-clear.w3-center
      %h2.w3-opacity Submit a Request
    :css
      * {
          box-sizing: border-box;
      }
      
      div#main {
        background-color: #f1f1f1;
      }
      
      input[type=text], select, textarea {
          width: 100%;
          padding: 12px;
          border: 1px solid #ccc;
          border-radius: 4px;
          resize: vertical;
      }
      
      label {
          padding: 12px 12px 12px 0;
          display: inline-block;
      }
      
      inputemail {
        width: 100%;
          padding: 12px;
          border: 1px solid #ccc;
          border-radius: 4px;
          resize: vertical;
      }
      
      input[type=submit] {
          background-color: #4CAF50;
          color: white;
          padding: 12px 20px;
          border: none;
          border-radius: 4px;
          cursor: pointer;
          float: right;
      }
      
      input[type=submit]:hover {
          background-color: #45a049;
      }
      
      .container {
          border-radius: 5px;
          background-color: #f2f2f2;
          padding: 20px;
      }
      
      .col-25 {
          float: left;
          width: 25%;
          margin-top: 6px;
          margin-left: 200px;
      }
      
      .col-75 {
          float: left;
          width: 75%;
          margin-top: 6px;
          margin-left: 200px;
      }
      
      /* Clear floats after the columns */
      .row:after {
          content: "";
          display: table;
          clear: both;
      }
      
      /* Responsive layout - when the screen is less than 600px wide, make the two columns stack on top of each other instead of next to each other */
      @media screen and (max-width: 600px) {
          .col-25, .col-75, input[type=submit] {
              width: 100%;
              margin-top: 0;
          }
      }

      
%body
.container
  %form
  = form_for(:request, url: requests_path) do |f| 
    .row
      .col-25
        = f.label :name, class: "label"
      .col-75
        = f.text_field :name, class: "input#fname"
    .row
      .col-25
        = f.label :email, class: "label"
      .col-75
        = f.email_field :email, class: "inputemail", style: "\r\n    width: 100%;\r\n    padding: 12px;\r\n    border: 1px solid #ccc;\r\n    border-radius: 4px;\r\n    resize: vertical;\r\n"
    .row
      .col-25
        = f.label :address, class: "label"
      .col-75
        = f.text_field :address, class: "input#address", style: "\r\n    width: 100%;\r\n    padding: 12px;\r\n    border: 1px solid #ccc;\r\n    border-radius: 4px;\r\n    resize: vertical;\r\n"
    .row
      .col-25
        = f.label :option, class: "label"
      .col-75
        = f.select :option,options_for_select(["Dishwasher","Disposal","Dryer","Refrigerator","Shower","Washer","Water Heater","Other"])
    .row
      .col-25
        = f.label :Subject, class: "label"
      .col-75
        = f.text_area :body, class: "textarea#subject"
    .row
      = f.submit :Submit, class: "input"
     

app/views/movies/show.html.haml
-# in app/views/movies/show.html.haml

/%h2 Details about #{@movie.title}

/%ul#details
 / %li
  /  Rating:
   / = @movie.rating
  /%li
   / Released on:
  /  = @movie.release_date.strftime("%B %d, %Y")

/%h3 Description:

/%p#description= @movie.description

/= link_to 'Edit', edit_movie_path(@movie)
/= button_to 'Delete', movie_path(@movie), :method => :delete, :confirm => 'Are you sure?'
/= link_to 'Back to movie list', movies_path