config/routes.rb
Rails.application.routes.draw do
  resources :requests
  get 'messages/new'

  get 'sessions/new'

  root 'sessions#new'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

	get '/messages', to: 'messages#messages'
	post '/send', to: 'messages#create'
	get '/error', to: 'messages#error'
	get '/LandLord/Send', to:'messages#landLord_send'
	get 'LandLord/Error', to: 'messages#landLord_error'
	get '/reply', to: 'messages#reply'
  

  get '/home', to: 'movies#dashboard'

  get '/tenant_maintenance', to: 'requests#tenant_maintenance'

  get '/requestform', to: 'movies#requestform'
  get '/documents', to: 'movies#documents'
  get '/pay_rent', to: 'movies#pay_rent'
  get '/profile', to: 'movies#profile'
  get '/settings', to: 'movies#settings'
  
  get '/send', to: 'movies#send'
  get '/LandLord', to: 'movies#landLord'#, as: 'landLord'
  get '/LandLord/TennantList', to: 'movies#tennantList', as: 'tennantList'
  get '/LandLord/Messages', to: 'movies#messages_landLord', as: 'landLordMessages'
  get '/LandLord/Documents', to: 'movies#documents_landLord', as: 'landLordDocuments'
  get '/LandLord/maintenance', to: 'movies#maintenance', as: 'maintenance'
  get '/LandLord/Profile', to: 'movies#profile_landLord', as: 'landLordProfile'
  resources :tenant

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'


  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  resources :users
	resources :messages
end

app/models/request.rb
#Request Model
class Request < ActiveRecord::Base

	validates :name, presence: true
	validates :email, presence: true
	validates :address, presence: true
	validates :option, presence: true
	validates :body, presence: true
end

app/controllers/requests_controller.rb
#controller for requests
class RequestsController < ApplicationController
   before_action :set_request, only: [:show, :edit, :update, :destroy]

  def requests
		@request = Request.new	
  end
  
#   def create
# 		@request = Request.new(message_params)
# 	end

  # GET /requests
  # GET /requests.json
  def index
    @requests = Request.all.where(name: current_user.name).order(:created_at)
  end
  
  def tenant_maintenance
    @requests = Request.all.where(name: current_user.name).order(:created_at)
  end

  # # GET /requests/1
  # # GET /requests/1.json
  # def show
  # end

  # GET /requests/new
  def new
    @request = Request.new
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(request_params)
    @request.status = "Incomplete"
    respond_to do |format|
      if @request.save
        #@request.status = "Incomplete"
        format.html { redirect_to @request, notice: 'Request was successfully created.' }
        format.json { render :show, status: :created, location: @request }
        updateTenant = Tenant.find_by_tenant(current_user.name)
			  @update = (updateTenant.maintenance).to_i + 1
			  Tenant.create!(:tenant => updateTenant.tenant,:email => updateTenant.email, :rent => updateTenant.rent, :unreadMess => updateTenant.unreadMess, :maintenance=>
        @update, :propLoc => updateTenant.propLoc)
        updateTenant.destroy
      else
        format.html { render :new }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to @request, notice: 'Request was successfully updated.' }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request.destroy
    respond_to do |format|
      format.html { redirect_to requests_url, notice: 'Request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

	def display_name(email)
		User.find_by(email: email).name
	end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params.require(:request).permit(:name, :email, :address, :option, :body, :status)

    end
end

app/helpers/requests_helper.rb
#Helper for requests
module RequestsHelper
    
    def get_sent
		Request.where(email: current_user.email).all
	end

	def get_all
		Request.all
	end
	
	def get_incomplete
	    Request.where(email: current_user.email, status: "incomplete").all
	end
	
	def get_complete
	    Request.where(email: current_user.email, status: "complete").all
	end
	
end

app/views/requests/_form.html.erb
<%= form_for(@request) do |f| %>
  <% if @request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% @request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :option %><br>
    <%= f.text_field :option %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/requests/edit.html.erb
<h1>Editing Request</h1>

<%= render 'form' %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', tenant_maintenance_path %>

app/views/requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Requests</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Address</th>
      <th>Option</th>
      <th>Body</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
      <tr>
        <td><%= request.name %></td>
        <td><%= request.email %></td>
        <td><%= request.address %></td>
        <td><%= request.option %></td>
        <td><%= request.body %></td>
        <td><%= request.status %></td>
        <td><%= link_to 'Show', request %></td>
        <td><%= link_to 'Edit', edit_request_path(request) %></td>
        <td><%= link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Request', tenant_maintenance_path %>

app/views/requests/new.html.erb
<h1>New Request</h1>

<%= render 'form' %>

<%= link_to 'Back', tenant_maintenance_path %>

app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @request.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @request.email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @request.address %>
</p>

<p>
  <strong>Option:</strong>
  <%= @request.option %>
</p>

<p>
  <strong>Body:</strong>
  <%= @request.body %>
</p>

<p>
  <strong>Status:</strong>
  <%= @request.status %>
</p>


<%= link_to 'Edit', edit_request_path(@request) %> |
<%= link_to 'Back', requestform_path %>

app/views/requests/tenant_maintenance.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Maintenance Requests
    %meta{:charset => "UTF-8"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %link{:href => "https://www.w3schools.com/w3css/4/w3.css", :rel => "stylesheet"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Raleway", :rel => "stylesheet"}/
    %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css", :rel => "stylesheet"}/
    :css
      html,body,h1,h2,h3,h4,h5 {font-family: "Raleway", sans-serif}
         
  %body
    .w3-panel.w3-clear.w3-center
      %h2.w3-opacity Maintenance Requests
    :css
      * {
          box-sizing: border-box;
      }
      
      input[type=text], select, textarea {
          width: 100%;
          padding: 12px;
          border: 1px solid #ccc;
          border-radius: 4px;
          resize: vertical;
      }
      
      label {
          padding: 12px 12px 12px 0;
          display: inline-block;
      }
      
      input[type=submit] {
          background-color: #4CAF50;
          color: white;
          padding: 12px 20px;
          border: none;
          border-radius: 4px;
          cursor: pointer;
          float: right;
      }
      
      input[type=submit]:hover {
          background-color: #45a049;
      }
      
      .container {
          border-radius: 5px;
          background-color: #f2f2f2;
          padding: 20px;
      }
      
      .col-25 {
          float: left;
          width: 25%;
          margin-top: 6px;
          margin-left: 200px;
      }
      
      .col-75 {
          float: left;
          width: 75%;
          margin-top: 6px;
          margin-left: 200px;
      }
      
       .limiter {
       width: 1366px;
       margin: 0 auto;
      }

      .container-table100 {
       width: 100%;
       /min-height: 100vh;
       /background: #fff;
       display: -webkit-box;
       display: -webkit-flex;
       display: -moz-box;
       display: -ms-flexbox;
       display: flex;
       align-items: center;
       justify-content: center;
       flex-wrap: wrap;
       /padding: 33px 30px;
      }

      .wrap-table100 {
       width: 1170px;
      }

      .table100 {
       background-color: #fff;
      }

      table {
       width: 100%;
      }

      th, td {
       font-weight: unset;
       padding-right: 10px;
      }

      .column1 {
       width: 14%;
       padding-left: 40px;
      }

      .column2 {
       width: 13%;
      }

      .column3 {
       width: 22%;
      }

      .column4 {
       width: 14%;
      }

      .column5 {
       width: 19%;
      }
      
      .column6 {
       width: 14%;
      }
      
      .column7 {
       width: 14%;
      }

      .table100-head th {
       padding-top: 18px;
       padding-bottom: 18px;
      }

      .table100-body td {
       padding-top: 16px;
       padding-bottom: 16px;
      }
      
      .table100.ver1 th {
       font-family: Lato-Bold;
       font-size: 18px;
       color: #fff;
       line-height: 1.4;

       background-color: #6c7ae0;
      }

      .table100.ver1 td {
       font-family: Lato-Regular;
       font-size: 15px;
       color: #808080;
       line-height: 1.4;
      }

      .table100.ver1 .table100-body tr:nth-child(even) {
       background-color: #f8f6ff;
      }
      /* Clear floats after the columns */
      .row:after {
          content: "";
          display: table;
          clear: both;
      }
      
      /* Responsive layout - when the screen is less than 600px wide, make the two columns stack on top of each other instead of next to each other */
      @media screen and (max-width: 600px) {
          .col-25, .col-75, input[type=submit] {
              width: 100%;
              margin-top: 0;
          }
      }
      button {
        border: none;
        outline: 0;
        display: inline-block;
        padding: 8px;
        color: white;
        background-color: #000;
        text-align: center;
        cursor: pointer;
        width: 30%;
        font-size: 18px;
        margin: center;
        margin-left: 500px;
        margin-top: 40px;
      }
      
   

  %body
  .limiter
  .container-table100
    .wrap-table100
      .table100.ver1.m-b-110
        .table100-head
          %table
            %thead
              %tr.row100.head
                %th.cell100.column1 Name
                %th.cell100.column2 Email
                %th.cell100.column3 Address
                %th.cell100.column4 Request
                %th.cell100.column5 Subject
                %th.cell100.column6 Time Created
                %th.cell100.column7 Status
        .table100-body.js-pscroll
          %table
            %tbody
            - @requests.each do |request|
              %tr.row100.body
                %td.cell100.column1= request.name
                %td.cell100.column2= request.email
                %td.cell100.column3= request.address
                %td.cell100.column4= request.option
                %td.cell100.column5= request.body
                %td.cell100.column6= request.created_at
                %td.cell100.column7= request.status
                

    // .w3-container
    //   %table.w3-table-all
    //     %thead
    //       %tr.w3-red
    //         .test1 Name
    //         %th Email
    //         %th Address
    //         %th Request
    //         %th Subject
    //         %th Time of Request
    //         %th Status
    // - @requests.each do |request|
    //   %tr
    //     .test1= request.name
    //     .test= request.email
    //     .test= request.address
    //     .test= request.option
    //     .test= request.body
    //     .test= request.status
    //     .test= request.created_at
    //     // %td= link_to 'Show', request
    //     // %td= link_to 'Edit', edit_request_path(request)
    //     // %td= link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' }
        
  %body
    %p
    %button{:onclick => "window.location.href='/requestform'"} Submit a New Request
    /%button.w3-button.w3-block.w3-black{:style => "width:30%"} Button